# Generated by Django 6.0.2 on 2026-03-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_user_notifications_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('product', 'Producto'), ('message', 'Mensaje')], default='product', max_length=10),
        ),
    ]
