# Generated by Django 6.0.2 on 2026-03-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_messages',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='user',
            name='messages_used_this_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='products_used',
            field=models.IntegerField(default=0),
        ),
    ]
