# Generated by Django 6.0.2 on 2026-03-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_user_max_messages_user_messages_used_this_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
