# Generated by Django 6.0.2 on 2026-03-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='stock',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
