# Generated by Django 6.0.2 on 2026-03-25 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_like_unique_together_remove_post_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
