# Generated by Django 6.0.2 on 2026-03-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
