# Generated by Django 6.0.2 on 2026-03-25 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_alter_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
