# Generated by Django 6.0.2 on 2026-03-25 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_remove_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('post', 'Producto'), ('message', 'Mensaje'), ('user', 'Usuario')], max_length=10)),
                ('content_id', models.IntegerField()),
                ('type', models.CharField(choices=[('inappropriate', 'Contenido inapropiado'), ('spam', 'Spam'), ('fake', 'Producto falso'), ('other', 'Otro')], max_length=20)),
                ('reason', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
