# Generated by Django 6.0.2 on 2026-03-26 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_user_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verification_sent_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
