# Generated by Django 6.0.2 on 2026-03-26 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_faq_supportticket_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.supportticket'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('follow', 'Nuevo seguidor'), ('like_post', 'Me gusta en producto'), ('like_message', 'Me gusta en mensaje'), ('new_post', 'Nuevo producto'), ('new_message', 'Nuevo mensaje'), ('ticket_reply', 'Respuesta en ticket de soporte'), ('order', 'Nuevo pedido')], max_length=20),
        ),
    ]
