# Generated by Django 6.0.2 on 2026-03-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_remove_cart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='allow_backorder',
            field=models.BooleanField(default=False, help_text='Permitir pedidos sin stock disponible'),
        ),
        migrations.AddField(
            model_name='post',
            name='discount_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='discount_limit_quantity',
            field=models.IntegerField(default=0, help_text='Cantidad máxima para aplicar descuento (0 = ilimitado)'),
        ),
        migrations.AddField(
            model_name='post',
            name='discount_limit_type',
            field=models.CharField(choices=[('quantity', 'Por cantidad'), ('time', 'Por tiempo'), ('none', 'Sin límite')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='discount_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto fijo')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Producto destacado en la tienda'),
        ),
        migrations.AddField(
            model_name='post',
            name='low_stock_threshold',
            field=models.IntegerField(default=5, help_text='Alertar cuando el stock baje de este número'),
        ),
        migrations.AddField(
            model_name='post',
            name='max_per_order',
            field=models.IntegerField(default=0, help_text='Máximo unidades por pedido (0 = sin límite)'),
        ),
        migrations.AddField(
            model_name='post',
            name='sales_count',
            field=models.IntegerField(default=0, help_text='Número de unidades vendidas'),
        ),
        migrations.AddField(
            model_name='post',
            name='wholesale_min_quantity',
            field=models.IntegerField(default=0, help_text='Cantidad mínima para aplicar precio mayorista'),
        ),
        migrations.AddField(
            model_name='post',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category'], name='client_post_categor_88ade6_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_active'], name='client_post_is_acti_c1a7f3_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_featured'], name='client_post_is_feat_ba373c_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at'], name='client_post_created_26bef3_idx'),
        ),
    ]
