# Generated by Django 6.0.2 on 2026-03-27 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_post_allow_backorder_post_discount_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='client_post_categor_88ade6_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='client_post_is_acti_c1a7f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='client_post_is_feat_ba373c_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='client_post_created_26bef3_idx',
        ),
        migrations.RemoveField(
            model_name='post',
            name='allow_backorder',
        ),
        migrations.RemoveField(
            model_name='post',
            name='discount_end_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='discount_limit_quantity',
        ),
        migrations.RemoveField(
            model_name='post',
            name='discount_limit_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='discount_start_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='post',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='post',
            name='low_stock_threshold',
        ),
        migrations.RemoveField(
            model_name='post',
            name='max_per_order',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sales_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='wholesale_min_quantity',
        ),
        migrations.RemoveField(
            model_name='post',
            name='wholesale_price',
        ),
    ]
